apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-db
  template:
    metadata:
      labels:
        app: feedback-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: feedback-config
            - secretRef:
                name: feedback-secrets
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: feedback-db-storage
      volumes:
        - name: feedback-db-storage
          persistentVolumeClaim:
            claimName: feedback-db-pvc
