apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  labels:
    app: feedback-service
spec:
  type: ClusterIP
  selector:
    app: feedback-service
  ports:
    - port: 80
      targetPort: 8080
